<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Arial, sans-serif; color: #333; line-height: 1.6; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        h2 { color: #2c3e50; }
        table { border-collapse: collapse; width: 100%; margin: 15px 0; }
        th, td { padding: 8px 12px; text-align: left; border: 1px solid #ddd; }
        th { background: #f8f9fa; font-weight: 600; }
        .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #eee; font-size: 12px; color: #999; }
    </style>
</head>
<body>
<div class="container">
    <h2>{{ $reportName }}</h2>
    <p>Your scheduled report has been generated on {{ now()->format('d M Y \\a\\t H:i') }}.</p>

    <h3>Summary</h3>
    <table>
        @foreach($summary as $key => $value)
            @if(!is_array($value))
                <tr>
                    <th>{{ ucfirst(str_replace('_', ' ', $key)) }}</th>
                    <td>{{ $value }}</td>
                </tr>
            @endif
        @endforeach
    </table>

    @if($outputFormat === 'csv')
        <p>The full report is attached as a CSV file.</p>
    @endif

    <div class="footer">
        Generated by Care OS — Omega Life UK
    </div>
</div>
</body>
</html>
